server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb   # Configuración de conexión H2 en memoria
    username: sa              # Usuario por defecto de H2
    password:                 # Contraseña por defecto de H2
  jpa:
    hibernate:
      ddl-auto: create
    database: h2              # Usar la base de datos H2
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
